---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: ankur
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "ankur2k19/scientific-calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Remove existing container (if any)
      shell: docker rm -f scientific-calculator || true

    - name: Run Scientific Calculator container
      shell: docker run -it -d --name scientific-calculator -p 8501:8501 ankur2k19/scientific-calculator

    - name: Open Streamlit app in browser
      shell: xdg-open http://localhost:8501
      when: ansible_facts['os_family'] == "Debian"
